### Note

+ This file is designed for the homework 2 of AIT 736; 
+ Author: Xu He （hexu1124746@gmail.com）
+ Date: 2019.Oct.15

1. *Gennerate sample dataset*
   + generate a binary classfication dataset and a regression test dataset
   + split the dataset, select 2/3 of data as the training data and 1/3 as the test data

In [31]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
import time
#import matplotlib.pyplot as plt
#%matplotlib inline

#Generate the classfication dataset
data,target=datasets.make_classification(n_samples=800, n_features=6, n_informative=3, n_redundant=2,n_repeated=1, n_classes=2, n_clusters_per_class=1)
print('the size of classfication dataset is:', data.shape, '\n')

labels = np.where(target>0, 1, -1)
#plt.scatter(data[:,0],data[:,1],c=target)
#plt.show()
print('negative label\n')

train_features, test_features, train_labels, test_labels = train_test_split(data, labels, test_size=0.33)
print('The training data for classfication:\n', train_features[0:5], '\n')


#Generate the regression dataset
data_r, target_r = datasets.make_regression(n_samples=800, n_features=6, noise=0.1)
print('the size of regression dataset is:', data.shape, '\n')
train_features_r, test_features_r, train_values, test_values = train_test_split(data_r, target_r, test_size=0.33)
print('The training data for regression:\n', train_features_r[0:5])

the size of classfication dataset is: (800, 6) 

the label includes:1 = positive label; -1 = negative label

The training data for classfication:
 [[ 0.12670648 -1.69552288  0.69868011 -0.96748874  0.12670648  0.041724  ]
 [ 0.02835739  0.38913356 -3.86943531 -2.9984682   0.02835739 -3.84619401]
 [-1.82365823  0.2623654  -1.31011613 -1.31250531 -1.82365823 -2.97614242]
 [ 0.10649974 -1.45622289  0.7390689  -0.71029143  0.10649974  0.17945023]
 [-0.45995957  1.36934156 -0.94153035  0.37033336 -0.45995957 -0.76819455]] 

the size of regression dataset is: (800, 6) 

The training data for regression:
 [[-0.16689177 -0.67608568  0.59203041 -1.06257812 -0.05221234  0.0736683 ]
 [-1.80626278 -0.47135561  0.28951554 -0.06520391 -1.23784607  0.24657205]
 [-0.24380784 -0.45498547  0.05708566 -0.45098203  0.69816411  1.77911496]
 [-0.25308285 -1.11375675 -2.24127431  1.25552681  0.12174644  0.80785513]
 [-0.47567008  0.77395238 -0.01688227  0.43406425  0.46323679 -0.63385941]]


2. *PLA*
   + train the perceptron model and predict the labels based on the training and test data, respectively;
   + compute the training time and the prediction accruacy
   + Note:the specific implemention code of perceptron is encapsulated in the perceptron.py, and you can see detailed comments in this file.

In [41]:
import perceptron as per # 
time_1 = time.time()

p = per.Perceptron()
p.train(train_features, train_labels)

time_2 = time.time()
print('training cost ', time_2 - time_1, ' second', '\n')

test_predict = p.predict(test_features)

score = accuracy_score(test_labels, test_predict) # calculate the accracy
print("The accruacy socre is ", score)

training cost  0.0456540584564209  second 

The accruacy socre is  0.9318181818181818


3. *Linear Regression*
   + LR algorithm can be used for both regression and classfication task. Here, we test LR in two dataset for its performance in classfication and regression, respectively.
   + compute the training time and the prediction accruacy
   + Note:the specific implemention code of Linear Regression is encapsulated in the linearRegression.py, and you can see detailed comments in this file.

In [33]:
# This cell make a classfication task
import linearRegression as lr
from imp import reload
reload(lr)

time_3 = time.time()
l_c = lr.linearRegression()
l_c.train(train_features,train_labels)

time_4 = time.time()
print('training cost ', time_4 - time_3, ' second', '\n')

label_predict = l_c.predict(test_features)
score = accuracy_score(test_labels, label_predict)
print("The accruacy socre is ", score)

training cost  0.0009920597076416016  second 

The accruacy socre is  0.928030303030303


In [34]:
# This cell make a regression task
time_5 = time.time()

l_r = lr.linearRegression()
l_r.train(train_features_r,train_values)

time_6 = time.time()
print('training cost ', time_6 - time_5, ' second', '\n')

values_predict = l_r.predict_regression(test_features_r)

score_r = mean_squared_error(test_values, values_predict)
print("The mean square error: ", score_r)

training cost  0.002991914749145508  second 

The mean square error:  0.010096611809569452
